const SPOTIFY_SCOPES = [
  'user-read-private',
  'user-library-read',
  'user-library-modify',
  'playlist-read-private',
  'playlist-modify-private',
  'playlist-modify-public',
];

const SPOTIFY_STORAGE_KEYS = {
  token: 'musicdigger.spotify.token',
  verifier: 'musicdigger.spotify.verifier',
  state: 'musicdigger.spotify.state',
};

const DEFAULT_VISIBLE_GENRES = 4;
const BACKEND_REQUEST_TIMEOUT_MS = 1800;
const MAX_MAP_PREVIEW_TRACKS = 4;
const MAP_SURFACE_WIDTH = 1800;
const MAP_SURFACE_HEIGHT = 1280;
const MAP_MIN_NODE_GAP = 16;
const MAP_ZOOM_STEP = 0.2;
const MAP_MIN_ZOOM = 0.7;
const MAP_MAX_ZOOM = 2.2;
const MAP_DRAG_THRESHOLD = 6;

const MAP_FAMILIES = [
  {
    id: 'pulse',
    label: 'Pulse',
    centerX: 18,
    centerY: 24,
    color: '#ff8c69',
    keywords: ['hip-hop', 'hiphop', 'rap', 'trap', 'grime', 'drill', 'boom-bap'],
  },
  {
    id: 'spectrum',
    label: 'Spectrum',
    centerX: 49,
    centerY: 18,
    color: '#31c7ea',
    keywords: ['pop', 'dance', 'k-pop', 'edm', 'house', 'electro', 'disco'],
  },
  {
    id: 'distortion',
    label: 'Distortion',
    centerX: 76,
    centerY: 34,
    color: '#f3c968',
    keywords: ['rock', 'indie', 'alternative', 'punk', 'metal', 'grunge'],
  },
  {
    id: 'afterglow',
    label: 'Afterglow',
    centerX: 32,
    centerY: 74,
    color: '#9d7bff',
    keywords: ['jazz', 'lofi', 'lo-fi', 'ambient', 'soul', 'r-n-b', 'rnb', 'folk'],
  },
  {
    id: 'horizon',
    label: 'Horizon',
    centerX: 72,
    centerY: 74,
    color: '#73d6a8',
    keywords: ['classical', 'country', 'soundtrack', 'world', 'acoustic'],
  },
];

const BUILTIN_GENRES = [
  {
    id: 'hiphop',
    name: 'Hip-Hop',
    description: '리듬과 랩 중심의 장르',
    subgenres: ['jazz-hiphop', 'trap'],
    similar: ['rnb'],
    fusion: ['boom-bap'],
    tracks: [
      { title: 'SICKO MODE', artist: 'Travis Scott' },
      { title: 'HUMBLE.', artist: 'Kendrick Lamar' },
      { title: "God's Plan", artist: 'Drake' },
      { title: 'In Da Club', artist: '50 Cent' },
      { title: 'Lose Yourself', artist: 'Eminem' },
      { title: 'Stronger', artist: 'Kanye West' },
      { title: 'Empire State Of Mind', artist: 'JAY-Z feat. Alicia Keys' },
      { title: 'Hot In Herre', artist: 'Nelly' },
    ],
  },
  {
    id: 'jazz-hiphop',
    name: 'Jazz Hip-Hop',
    description: '재즈 화성과 힙합 비트가 결합된 부드러운 그루브',
    subgenres: [],
    similar: ['lofi'],
    fusion: [],
    tracks: [
      { title: 'Feather', artist: 'Nujabes' },
      { title: 'Luv(sic.) pt3', artist: 'Nujabes' },
      { title: 'Aruarian Dance', artist: 'Nujabes' },
      { title: 'Rebirth of Slick (Cool Like Dat)', artist: 'Digable Planets' },
      { title: 'Electric Relaxation', artist: 'A Tribe Called Quest' },
      { title: 'Award Tour', artist: 'A Tribe Called Quest' },
      { title: "Runnin'", artist: 'The Pharcyde' },
      { title: 'Passing Me By', artist: 'The Pharcyde' },
    ],
  },
  {
    id: 'trap',
    name: 'Trap',
    description: '강한 베이스와 하이햇이 특징인 현대 힙합',
    subgenres: [],
    similar: ['hiphop'],
    fusion: [],
    tracks: [
      { title: 'Mask Off', artist: 'Future' },
      { title: 'goosebumps', artist: 'Travis Scott' },
      { title: 'Bad and Boujee', artist: 'Migos feat. Lil Uzi Vert' },
      { title: 'XO TOUR Llif3', artist: 'Lil Uzi Vert' },
      { title: 'Life Is Good', artist: 'Future feat. Drake' },
      { title: 'pick up the phone', artist: 'Young Thug & Travis Scott feat. Quavo' },
      { title: 'Drip Too Hard', artist: 'Lil Baby & Gunna' },
      { title: 'FE!N', artist: 'Travis Scott feat. Playboi Carti' },
    ],
  },
  {
    id: 'boom-bap',
    name: 'Boom Bap',
    description: '킥과 스네어가 선명한 클래식 힙합 스타일',
    subgenres: [],
    similar: ['hiphop'],
    fusion: [],
    tracks: [
      { title: 'N.Y. State of Mind', artist: 'Nas' },
      { title: 'Mass Appeal', artist: 'Gang Starr' },
      { title: 'Shook Ones, Pt. II', artist: 'Mobb Deep' },
      { title: 'C.R.E.A.M.', artist: 'Wu-Tang Clan' },
      { title: 'Juicy', artist: 'The Notorious B.I.G.' },
      { title: 'The World Is Yours', artist: 'Nas' },
      { title: 'Protect Ya Neck', artist: 'Wu-Tang Clan' },
      { title: 'It Was A Good Day', artist: 'Ice Cube' },
    ],
  },
  {
    id: 'r-n-b',
    name: 'R&B',
    description: '보컬과 그루브 중심의 감각적인 장르',
    subgenres: [],
    similar: ['hiphop'],
    fusion: [],
    tracks: [
      { title: 'Blinding Lights', artist: 'The Weeknd' },
      { title: 'Location', artist: 'Khalid' },
      { title: 'Earned It', artist: 'The Weeknd' },
      { title: 'We Belong Together', artist: 'Mariah Carey' },
      { title: 'No Scrubs', artist: 'TLC' },
      { title: 'Say My Name', artist: "Destiny's Child" },
      { title: 'Adorn', artist: 'Miguel' },
      { title: 'U Remind Me', artist: 'Usher' },
    ],
  },
  {
    id: 'lofi',
    name: 'Lo-Fi',
    description: '편안하고 거친 질감의 비트 중심 장르',
    subgenres: [],
    similar: ['jazz-hiphop'],
    fusion: [],
    tracks: [
      { title: 'affection', artist: 'Jinsang' },
      { title: 'snowman', artist: 'WYS' },
      { title: 'day 7', artist: 'potsu' },
      { title: 'I wish it would never stop snowing', artist: 'sleepdealer' },
      { title: 'Luv Letter', artist: 'Jinsang' },
      { title: 'warm nights', artist: 'xander.' },
      { title: 'Monday Loop', artist: 'Tomppabeats' },
      { title: 'glow', artist: 'bsd.u' },
    ],
  },
];

const state = {
  genres: [],
  filteredGenres: [],
  currentGenreId: null,
  currentView: 'home',
  genreListExpanded: false,
  isDarkMode: true,
  searchQuery: '',
  usingBackendGenres: false,
  mapLayoutById: new Map(),
  mapZoom: {
    main: 1,
    modal: 1,
  },
  mapViewportReady: {
    main: false,
    modal: false,
  },
  spotify: {
    configured: false,
    accessToken: null,
    refreshToken: null,
    expiresAt: 0,
    profile: null,
    playlists: [],
    likedTracks: [],
    likedTrackKeys: new Set(),
    trackUriCache: new Map(),
  },
};

const elements = {
  body: document.body,
  homeView: document.getElementById('home-view'),
  mapView: document.getElementById('map-view'),
  libraryView: document.getElementById('library-view'),
  profileView: document.getElementById('profile-view'),
  settingsView: document.getElementById('settings-view'),
  genreList: document.getElementById('genre-list'),
  genreToggle: document.getElementById('genre-toggle'),
  genreTitle: document.getElementById('genre-title'),
  genreDesc: document.getElementById('genre-desc'),
  trackList: document.getElementById('track-list'),
  subgenres: document.getElementById('subgenres'),
  similar: document.getElementById('similar'),
  fusion: document.getElementById('fusion'),
  genreCount: document.getElementById('genre-count'),
  trackCount: document.getElementById('track-count'),
  relationCount: document.getElementById('relation-count'),
  heroTag: document.getElementById('hero-tag'),
  currentGenreChip: document.getElementById('current-genre-chip'),
  searchInput: document.getElementById('genre-search'),
  menuToggle: document.getElementById('menu-toggle'),
  menuPanel: document.getElementById('menu-panel'),
  menuSettings: document.getElementById('menu-settings'),
  sidebarRandom: document.getElementById('sidebar-random'),
  playerTrackTitle: document.getElementById('player-track-title'),
  playerTrackArtist: document.getElementById('player-track-artist'),
  playerBarTitle: document.getElementById('player-bar-title'),
  playerBarSubtitle: document.getElementById('player-bar-subtitle'),
  navHome: document.getElementById('nav-home'),
  navMap: document.getElementById('nav-map'),
  navLibrary: document.getElementById('nav-library'),
  navPlaylists: document.getElementById('nav-playlists'),
  navProfile: document.getElementById('nav-profile'),
  profileSlot: document.getElementById('profile-slot'),
  profileAvatar: document.getElementById('profile-avatar'),
  spotifyLibrary: document.getElementById('spotify-library'),
  spotifyAuthButton: document.getElementById('spotify-auth-button'),
  spotifyRefreshButton: document.getElementById('spotify-refresh-button'),
  spotifyProfileCard: document.getElementById('spotify-profile-card'),
  playlistSection: document.getElementById('playlist-section'),
  likedSection: document.getElementById('liked-section'),
  playlistList: document.getElementById('playlist-list'),
  likedTrackList: document.getElementById('liked-track-list'),
  profileScreenCard: document.getElementById('profile-screen-card'),
  profileSummary: document.getElementById('profile-summary'),
  profileSettingsBlock: document.getElementById('profile-settings-block'),
  profileThemeToggle: document.getElementById('profile-theme-toggle'),
  profileMoreSettings: document.getElementById('profile-more-settings'),
  profileSettingsNote: document.getElementById('profile-settings-note'),
  settingsThemeToggle: document.getElementById('settings-theme-toggle'),
  settingsOpenProfile: document.getElementById('settings-open-profile'),
  settingsOpenHome: document.getElementById('settings-open-home'),
  playlistModal: document.getElementById('playlist-modal'),
  playlistModalClose: document.getElementById('playlist-modal-close'),
  playlistForm: document.getElementById('playlist-form'),
  playlistName: document.getElementById('playlist-name'),
  playlistDescription: document.getElementById('playlist-description'),
  playlistPrivate: document.getElementById('playlist-private'),
  playlistSubmit: document.getElementById('playlist-submit'),
  mapCanvas: document.getElementById('genre-map-canvas'),
  mapSurface: document.getElementById('genre-map-surface'),
  mapVisibleCount: document.getElementById('map-visible-count'),
  mapConnectionCount: document.getElementById('map-connection-count'),
  mapSelectionBadge: document.getElementById('map-selection-badge'),
  mapSelectionTitle: document.getElementById('map-selection-title'),
  mapSelectionDesc: document.getElementById('map-selection-desc'),
  mapSelectionLinks: document.getElementById('map-selection-links'),
  mapSelectionTracks: document.getElementById('map-selection-tracks'),
  mapOpenHome: document.getElementById('map-open-home'),
  mapZoomIn: document.getElementById('map-zoom-in'),
  mapZoomOut: document.getElementById('map-zoom-out'),
  mapZoomReset: document.getElementById('map-zoom-reset'),
  mapZoomLevel: document.getElementById('map-zoom-level'),
  mapOpenModal: document.getElementById('map-open-modal'),
  mapModal: document.getElementById('map-modal'),
  mapModalClose: document.getElementById('map-modal-close'),
  mapModalCanvas: document.getElementById('genre-map-modal-canvas'),
  mapModalSurface: document.getElementById('genre-map-modal-surface'),
  mapModalZoomIn: document.getElementById('map-modal-zoom-in'),
  mapModalZoomOut: document.getElementById('map-modal-zoom-out'),
  mapModalZoomReset: document.getElementById('map-modal-zoom-reset'),
  mapModalZoomLevel: document.getElementById('map-modal-zoom-level'),
};

export {
  BACKEND_REQUEST_TIMEOUT_MS,
  BUILTIN_GENRES,
  DEFAULT_VISIBLE_GENRES,
  MAP_DRAG_THRESHOLD,
  MAP_FAMILIES,
  MAP_MAX_ZOOM,
  MAP_MIN_NODE_GAP,
  MAP_MIN_ZOOM,
  MAP_SURFACE_HEIGHT,
  MAP_SURFACE_WIDTH,
  MAP_ZOOM_STEP,
  MAX_MAP_PREVIEW_TRACKS,
  SPOTIFY_SCOPES,
  SPOTIFY_STORAGE_KEYS,
  elements,
  state,
};
